{{- $serviceName := .Values.serviceName -}}
---
{{- if or .Values.websitesAuto .Values.adminDomain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.autoAnnotations -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-auto-certs" ((include "backend2.name" .)) }}
spec:
  rules:
  {{- range .Values.websitesAuto }}
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
            path: '/'
            pathType: Prefix
          - backend:
              service:
                name: collab-backend
                port:
                  name: http
            path: '/collab'
            pathType: Prefix
  {{- end }}
  {{- if .Values.adminDomain }}
    - host: {{ .Values.adminDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "backend2.adminName" . }}
                port:
                  name: http
              path: '/'
              pathType: Prefix
  {{- end }}
  tls:
  {{- range .Values.websitesAuto }}
    - hosts:
        - {{ .domain | quote }}
        {{- if not .ignoreWww }}
        - {{ printf "www.%s" .domain | quote }}
        {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
---
{{- if .Values.websitesManual }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.manualAnnotations -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-manual-certs" ((include "backend2.name" .)) }}
spec:
  rules:
  {{- range .Values.websitesManual }}
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
            path: '/'
            pathType: Prefix
          - backend:
              service:
                name: collab-backend
                port:
                  name: http
            path: '/collab'
            pathType: Prefix
  {{- end }}
  tls:
  {{- range .Values.websitesManual }}
    - hosts:
        - {{ .domain | quote }}
        {{- if not .ignoreWww }}
        - {{ printf "www.%s" .domain | quote }}
        {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
