# Generated by Django 3.0.7 on 2020-07-14 14:34

import core.lib
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Entity')),
                ('title', models.CharField(max_length=256)),
                ('is_folder', models.BooleanField(default=False)),
                ('upload', models.FileField(blank=True, max_length=512, null=True, upload_to=core.lib.generate_object_filename)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.FileFolder')),
            ],
            bases=('core.entity',),
        ),
    ]
