# Generated by Django 3.2.5 on 2021-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
