# Generated by Django 2.2.11 on 2020-04-21 09:21

import core.lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_filefolder_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='upload',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=core.lib.generate_object_filename),
        ),
    ]
