# Generated by Django 3.2.6 on 2021-08-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_migrate_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0002_filefolder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='last_scan',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ScanIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=256)),
                ('file_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_title', models.CharField(max_length=256)),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.filefolder')),
                ('file_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group')),
                ('file_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
