# Generated by Django 3.2.6 on 2021-09-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_scanincident_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanincident',
            options={'ordering': ('-date',)},
        ),
    ]
