# Generated by Django 3.2.6 on 2022-03-16 16:45

from django.db import migrations, models


def populate_read_access_weight(apps, schema_editor):
    # pylint: disable=unused-argument
    from file.models import prepare_read_access_weight
    FileFolder = apps.get_model('file', 'FileFolder')

    for file_folder in FileFolder.objects.all():
        file_folder.read_access_weight = prepare_read_access_weight(file_folder)
        file_folder.save()


class Migration(migrations.Migration):
    dependencies = [
        ('file', '0005_alter_scanincident_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='read_access_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_read_access_weight)
    ]
