# Generated by Django 3.2.6 on 2022-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_filefolder_read_access_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='rich_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
