# Generated by Django 3.2.13 on 2022-05-11 12:00

from django.db import migrations, models


def populate_write_access_weight(apps, schema_editor):
    # pylint: disable=unused-argument
    from core.utils.access import get_write_access_weight
    FileFolder = apps.get_model('file', 'FileFolder')

    for file_folder in FileFolder.objects.all():
        try:
            file_folder.write_access_weight = get_write_access_weight(file_folder)
            file_folder.save()
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ('file', '0007_filefolder_rich_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='write_access_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_write_access_weight, migrations.RunPython.noop),
    ]
