# Generated by Django 3.2.14 on 2022-08-17 14:15

from django.db import migrations, models

def populate_type(apps, schema_editor):
    # pylint: disable=unused-argument
    FileFolder = apps.get_model('file', 'FileFolder')

    FileFolder.objects.filter(is_folder=True).update(type="Folder")
    FileFolder.objects.filter(is_folder=False).update(type="File")

class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_filefolder_write_access_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Folder', 'Folder'), ('Pad', 'Pad')], default='File', max_length=36),
        ),
        migrations.RunPython(
            populate_type,
            migrations.RunPython.noop
        ),
    ]
