# Generated by Django 3.2.14 on 2022-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_remove_filefolder_is_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='pad_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
