# Generated by Django 3.2.15 on 2022-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_filefolder_pad_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='last_download',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
