# Generated by Django 3.2.18 on 2023-03-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file', '0013_file_scan_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_fk', models.UUIDField(blank=True, null=True)),
                ('configuration', models.CharField(blank=True, max_length=256, null=True)),
                ('container_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='file.filefolder')),
            ],
        ),
    ]
