# Generated by Django 3.2.18 on 2023-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_filereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
