# Generated by Django 3.2.18 on 2023-04-03 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_filefolder_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
