# Generated by Django 2.2.2 on 2019-09-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wiki',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.Wiki'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='rich_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
