# Generated by Django 3.0.8 on 2020-08-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['position', 'created_at']},
        ),
    ]
