# Generated by Django 3.0.8 on 2020-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20200806_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
