# Generated by Django 3.1.8 on 2021-06-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wiki_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['position', 'published']},
        ),
    ]
