# Generated by Django 3.2.6 on 2022-02-03 14:53

from django.db import migrations

def forward_update_entity(apps, schema_editor):
    Wiki = apps.get_model('wiki', 'Wiki')
    Wiki.objects.filter(is_featured=True).update(tmp_is_featured=True)

def reverse_update_entity(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_rename_is_featured_wiki_old_is_featured'),
    ]

    run_before = [
        ('core', '0051_auto_20220203_1553'),
    ]

    operations = [
        migrations.RunPython(forward_update_entity, reverse_update_entity),
        migrations.RemoveField(
            model_name='wiki',
            name='is_featured',
        ),
    ]
