image: python:3.7

stages:
  - test
  - build
  - deploy

variables:
  SECRET_KEY: bg9kU6ckKXTLQeZxtovc
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  ENV: test
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  ELASTICSEARCH_URL: http://elasticsearch:9200
  ELASTICSEARCH_HOST: http://elasticsearch:9200

cache:
  paths:
  - $PIP_CACHE_DIR

before_script:

services:
  - postgres:latest
  - name: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    alias: elasticsearch
    command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]


prospector:
  stage: test
  tags:
    - docker
  script:
    - pip install -r requirements.txt
    - prospector --tool pylint --tool pep8 --uses django

test:
  stage: test
  tags:
    - docker
  script:
    - curl "http://elasticsearch:9200/_cat/health"
    - pip install -r requirements.txt
    - python manage.py test

build:
  stage: build
  tags:
    - shell
  only:
    - master
  script:
    - docker build -t registry.gitlab.com/pleio/backend2:${CI_COMMIT_SHA:0:8} .
    - docker build -t registry.gitlab.com/pleio/backend2:latest .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push registry.gitlab.com/pleio/backend2:${CI_COMMIT_SHA:0:8}
    - docker push registry.gitlab.com/pleio/backend2:latest

deploy-master:
  stage: deploy
  tags:
    - control-vps
  only:
    - master
  script:
    - /snap/bin/kubectl -n backend2 set image deployment/api api=registry.gitlab.com/pleio/backend2:${CI_COMMIT_SHA:0:8}
