image: python:latest

stages:
  - test
  - build
  - deploy

cache:
  paths:
  - ~/.cache/pip/

services:
  - postgres:latest

variables:
  SECRET_KEY: bg9kU6ckKXTLQeZxtovc
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres

before_script:
  - python -V
  - pip install -r requirements.txt
  - ls
  - cp ./docker/config.py backend2/config.py

prospector:
  stage: test
  tags:
    - docker
  script:
    - prospector --tool pylint --tool pep8 --uses django

test:
  stage: test
  tags:
    - docker
  script:
    - python manage.py test
