version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
  api:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-dev.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
  frontend:
    image: registry.gitlab.com/pleio/frontend:B2-latest
    restart: on-failure
    ports:
      - "9000:80"
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  storage:
    image: morrisjobke/docker-swift-onlyone
    ports:
     - "12345:8080"
    volumes:
      - storage_data:/srv
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  storage_data:
  esdata01:
    driver: local