version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
  api:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-dev.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
      - admin
      - localstack
  frontend:
    image: registry.gitlab.com/pleio/frontend:B2-latest
    restart: on-failure
    ports:
      - "9000:80"
  admin:
    build: .
    restart: on-failure
    environment:
      RUN_AS_ADMIN_APP: 'True'
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-admin-dev.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8888:8888"

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  storage:
    image: morrisjobke/docker-swift-onlyone
    ports:
     - "12345:8080"
    volumes:
      - storage_data:/srv
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
    - "1080:1080"
    - "1025:1025"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/home/localstack/data
    volumes:
      - "./.localstack:/home/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always

volumes:
  postgres_data:
  storage_data:
  localstack_data:
  esdata01:
    driver: local