version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
  api:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-dev.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
  frontend:
    image: registry.gitlab.com/pleio/frontend:B2-latest
    restart: on-failure
    ports:
      - "9000:80"

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: