version: '3'

services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-dev.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./.env
