version: '3'

services:
  api:
    build: .
    restart: on-failure
    environment:
      DEBUG: 'True'
      CELERY_BROKER_URL: 'amqp://rabbitmq'
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-dev.sh"]
    volumes:
      - .:/app
      - frontend-build:/app/frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - frontend
      - admin
      - localstack
      - rabbitmq
  background:
    build: .
    restart: on-failure
    environment:
      CELERY_BROKER_URL: 'amqp://rabbitmq'
    env_file:
      - ./.env
    stdin_open: true
    command: ["/start-background.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
      - localstack
      - rabbitmq
  frontend:
    image: registry.gitlab.com/pleio/frontend:latest
    volumes:
      - frontend-build:/shared
    command: "cp -Rp /usr/share/nginx/html/. /shared"
  admin:
    build: .
    restart: on-failure
    environment:
      RUN_AS_ADMIN_APP: 'True'
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    command: ["/start-admin-dev.sh"]
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8888:8888"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
    - "1080:1080"
    - "1025:1025"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://localhost?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  frontend-build:
  postgres_data:
  esdata01:
    driver: local