version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=qWxPJrZCLeHZraNTWjEKHdJJxJyho8
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
