# Generated by Django 3.0.8 on 2020-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200714_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='is_in_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
