# Generated by Django 2.2.6 on 2019-12-03 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191126_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_notifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='overview_email_interval',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_notification_email',
            field=models.BooleanField(default=False),
        ),
    ]
