# Generated by Django 3.0.8 on 2020-08-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200805_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefield',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profilefield',
            name='is_hidden',
        ),
    ]
