# Generated by Django 2.2.2 on 2019-09-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_auto_20190911_0732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('content_type', 'object_id', 'user', 'key')},
        ),
    ]
