# Generated by Django 2.2.2 on 2019-09-17 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190911_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='key',
            field=models.CharField(choices=[('bookmarked', 'Bookmarked'), ('voted', 'Voted'), ('followed', 'Followed')], default='bookmarked', max_length=16),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
