# Generated by Django 2.0 on 2018-07-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180717_1521'),
        ('core', '0004_auto_20180717_1341'),
    ]

    operations = [
    ]
