# Generated by Django 2.2.2 on 2019-09-17 15:15

import core.models.shared
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190917_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='read_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=core.models.shared.read_access_default, size=None),
        ),
        migrations.AlterField(
            model_name='entity',
            name='write_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=core.models.shared.write_access_default, size=None),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='read_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=core.models.shared.read_access_default, size=None),
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='write_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=core.models.shared.write_access_default, size=None),
        ),
    ]
