# Generated by Django 2.2.6 on 2019-12-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefield',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilefield',
            name='profile_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProfileField'),
        ),
        migrations.AlterField(
            model_name='userprofilefield',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
