# Generated by Django 2.2.6 on 2019-12-12 13:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191210_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Please provide valid JSON data'), blank=True, default=list, size=None)),
                ('position', models.IntegerField()),
                ('type', models.CharField(max_length=64)),
                ('parent_id', models.UUIDField(default=uuid.uuid4)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='core.Group')),
            ],
        ),
    ]
