# Generated by Django 2.2.2 on 2019-09-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190917_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-created_at']},
        ),
    ]
