# Generated by Django 2.0 on 2018-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_binaryfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='object_type',
        ),
    ]
