# Generated by Django 2.0 on 2018-07-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180718_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='container_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='object_type',
            new_name='container_type',
        ),
    ]
