# Generated by Django 3.1.2 on 2020-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_groupmembership_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_introduction_public',
            field=models.BooleanField(default=False),
        ),
    ]
