# Generated by Django 2.2.6 on 2020-01-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_column'),
        ('core', '0008_entityview_entityviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='cms.Page'),
        ),
    ]
