# Generated by Django 3.1.2 on 2020-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_group_is_introduction_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='notification_mode',
            field=models.CharField(choices=[('overview', 'overview'), ('direct', 'direct')], default='overview', max_length=10),
        ),
    ]
