# Generated by Django 2.0 on 2018-07-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180718_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='container_id',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='container_type',
            new_name='content_type',
        ),
    ]
