# Generated by Django 2.2.6 on 2020-01-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200120_0929'),
        ('core', '0010_subgroup'),
    ]

    operations = [
    ]
