# Generated by Django 3.1.2 on 2020-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201117_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='featured_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
