# Generated by Django 2.0 on 2018-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180718_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_2fa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_government',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='type',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('pending', 'Pending')], default='member', max_length=10),
        ),
    ]
