# Generated by Django 2.0.9 on 2018-11-20 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180917_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_open',
        ),
        migrations.AddField(
            model_name='group',
            name='auto_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='richDescription',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='welcome_message',
            field=models.TextField(default=''),
        ),
    ]
