# Generated by Django 2.2.6 on 2020-02-01 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20200130_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='overview_email_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
