# Generated by Django 2.0.9 on 2018-11-20 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181120_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
        migrations.AddField(
            model_name='group',
            name='plugins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=[], size=None),
        ),
    ]
