# Generated by Django 2.2.8 on 2020-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_auto_membership_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_leaving_group_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
