# Generated by Django 3.1.4 on 2021-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210106_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='featured_alt',
            field=models.CharField(default='', max_length=256),
        ),
    ]
