# Generated by Django 2.2.11 on 2020-03-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200309_1409'),
        ('core', '0014_auto_20200227_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='widget',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='cms.Column'),
        ),
    ]
