# Generated by Django 2.0.9 on 2018-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181120_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
