# Generated by Django 2.2.11 on 2020-03-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200309_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
