# Generated by Django 2.2.11 on 2020-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0016_groupmembership_enable_notification'), ('core', '0017_remove_userprofile_group_notifications')]

    dependencies = [
        ('core', '0015_auto_20200309_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='enable_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group_notifications',
        ),
    ]
