# Generated by Django 2.2.2 on 2019-07-09 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181121_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='plugins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
