# Generated by Django 2.2.11 on 2020-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_groupmembership_enable_notification_squashed_0017_remove_userprofile_group_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
