# Generated by Django 3.1.5 on 2021-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofilefield',
            name='value_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
