# Generated by Django 2.2.2 on 2019-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='richDescription',
            new_name='rich_description',
        ),
        migrations.AddField(
            model_name='group',
            name='is_membership_on_request',
            field=models.BooleanField(default=False),
        ),
    ]
