# Generated by Django 2.2.11 on 2020-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200311_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['group']},
        ),
    ]
