# Generated by Django 3.1.5 on 2021-02-08 12:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210208_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFieldValidator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('validator_data', models.JSONField(blank=True, help_text='Please provide valid JSON data', null=True)),
                ('validator_type', models.CharField(choices=[('inList', 'inList')], max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='profilefield',
            name='field_type',
            field=models.CharField(choices=[('select_field', 'select_field'), ('date_field', 'date_field'), ('html_field', 'html_field'), ('multi_select_field', 'multi_select_field'), ('text_field', 'text_field')], default='text_field', max_length=24),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='validators',
            field=models.ManyToManyField(related_name='profile_fields', to='core.ProfileFieldValidator'),
        ),
    ]
