# Generated by Django 2.2.2 on 2019-08-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190802_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_2fa_required',
        ),
        migrations.RemoveField(
            model_name='group',
            name='url',
        ),
    ]
