# Generated by Django 3.1.7 on 2021-03-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('core', '0019_auto_20210208_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_file', to='file.filefolder'),
        ),
    ]
