# Generated by Django 2.2.12 on 2020-05-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200421_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='overview_email_last_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
