# Generated by Django 2.2.2 on 2019-08-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190806_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.Group'),
        ),
        migrations.DeleteModel(
            name='BinaryFile',
        ),
    ]
