# Generated by Django 3.1.7 on 2021-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210324_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaccessrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
