# Generated by Django 2.2.2 on 2019-08-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190812_1446'),
        ('core', '0022_auto_20190812_0930'),
    ]

    operations = [
    ]
