# Generated by Django 3.1.7 on 2021-05-04 09:21

import core.models.attachment
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_siteaccessrequest_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('upload', models.FileField(blank=True, max_length=512, null=True, upload_to=core.models.attachment.attachment_path)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('upload', models.FileField(blank=True, max_length=512, null=True, upload_to=core.models.attachment.attachment_path)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('upload', models.FileField(blank=True, max_length=512, null=True, upload_to=core.models.attachment.attachment_path)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
