# Generated by Django 3.0.7 on 2020-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200528_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='is_in_overview',
            field=models.BooleanField(default=False),
        ),
    ]
