# Generated by Django 3.0.7 on 2020-07-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200421_0921'),
        ('core', '0023_profilefield_is_in_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='icon'
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_icon', to='file.FileFolder'),
        ),
    ]
