# Generated by Django 3.1.7 on 2021-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_commentattachment_entityattachment_groupattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
