# Generated by Django 2.2.2 on 2019-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_filefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
