# Generated by Django 3.2.4 on 2021-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='receive_notification_email',
            field=models.BooleanField(default=True),
        ),
    ]
