# Generated by Django 2.2.2 on 2019-08-28 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_filefolder_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Please provide valid JSON data', null=True)),
            ],
        ),
    ]
