# Generated by Django 3.2.4 on 2021-06-23 09:55

from django.db import migrations, models
import django.utils.timezone


def set_last_action(apps, schema_editor):
    Entity = apps.get_model('core', 'Entity')
    Entity.objects.update(last_action=models.F('created_at'))

def reverse_last_action(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_userprofile_receive_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_last_action, reverse_last_action),
    ]
