# Generated by Django 3.2.4 on 2021-06-07 11:26

from django.db import migrations, models
import django.utils.timezone


def set_published_date(apps, schema_editor):
    Entity = apps.get_model('core', 'Entity')
    Entity.objects.update(published=models.F('created_at'))

def reverse_published_date(apps, schema_editor):
    pass

def set_notifications_created(apps, schema_editor):
    Entity = apps.get_model('core', 'Entity')
    Entity.objects.update(notifications_created=True)

def reverse_notifications_created(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_group_featured_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['published']},
        ),
        migrations.AddField(
            model_name='entity',
            name='published',
            field=models.DateTimeField(null=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_published_date, reverse_published_date),
        migrations.AddField(
            model_name='entity',
            name='notifications_created',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_notifications_created, reverse_notifications_created),
    ]
