# Generated by Django 3.2.5 on 2021-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210607_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='notifications_created',
            field=models.BooleanField(default=False),
        ),
    ]
