# Generated by Django 3.2.4 on 2021-06-07 11:26

from django.db import migrations, models

def set_published_date(apps, schema_editor):
    Entity = apps.get_model('core', 'Entity')
    Entity.objects.update(published=models.F('created_at'))

def reverse_published_date(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_entity_notifications_created'),
    ]

    operations = [
        migrations.RunPython(set_published_date, reverse_published_date)
    ]
