# Generated by Django 3.2.6 on 2021-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_migrate_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_email_interval_hours',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='notification_mode',
            field=models.CharField(choices=[('disable', 'disable'), ('overview', 'overview'), ('direct', 'direct')], default='overview', max_length=10),
        )
    ]
