# Generated by Django 3.2.6 on 2021-08-13 11:07

from django.db import migrations, models

def set_disabled(apps, schema_editor):
    Entity = apps.get_model('core', 'GroupMembership')
    Entity.objects.filter(enable_notification=False).update(notification_mode='disable')

def reverse_set_disabled(apps, schema_editor):
    Entity = apps.get_model('core', 'GroupMembership')
    Entity.objects.filter(notification_mode='disable').update(notification_mode='overview', enable_notification=False)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210813_1101'),
    ]

    operations = [
        migrations.RunPython(set_disabled, reverse_set_disabled)
    ]
