# Generated by Django 3.2.6 on 2021-08-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_migrate_enable_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='enable_notification',
        ),
    ]
