# Generated by Django 3.2.6 on 2021-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sitestat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityattachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupattachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
