# Generated by Django 3.2.6 on 2021-10-21 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_annotation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.UUIDField(default=uuid.uuid4)),
                ('property', models.CharField(max_length=36)),
                ('data', models.JSONField()),
            ],
            options={
                'unique_together': {('content_id', 'property')},
            },
        ),
    ]
