# Generated by Django 3.2.6 on 2021-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_draftbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbackup',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
