# Generated by Django 3.2.6 on 2021-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_draftbackup_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrequest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
