# Generated by Django 3.2.6 on 2021-12-23 09:21

from django.conf import settings
from django.db import migrations, models
from django.db.models import deletion

def set_initial_attachment_owner(apps, schema_editor):
    Attachment = apps.get_model('core.Attachment')

    Attachment.objects.filter(attached_content_type=None).delete()
    for attachment in Attachment.objects.all():
        Model = apps.get_model(attachment.attached_content_type.app_label, attachment.attached_content_type.model)
        attached = Model.objects.get(id=attachment.attached_object_id)

        attachment.owner = attached.owner
        attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_auto_20211222_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_initial_attachment_owner, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(on_delete=deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
