# Generated by Django 3.2.6 on 2022-02-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_resizedimage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfileFieldSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_field', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_field_settings', to='core.group')),
                ('profile_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_settings', to='core.profilefield')),
            ],
        ),
    ]
