# Generated by Django 3.2.6 on 2022-02-03 14:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_groupprofilefieldsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tmp_is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='tmp_is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
