# Generated by Django 3.2.6 on 2022-02-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220203_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='tmp_is_featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='tmp_is_recommended',
            new_name='is_recommended',
        ),
    ]
