# Generated by Django 3.2.6 on 2022-02-22 12:11

from django.db import migrations

# The way images are resized is changed, deleting all will force a rerun of resizing.
def clear_resized_images(apps, _):
    ResizedImage = apps.get_model('core', 'ResizedImage')
    ResizedImage.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_is_archived'),
    ]

    operations = [
        migrations.RunPython(clear_resized_images, migrations.RunPython.noop)
    ]
