# Generated by Django 3.2.6 on 2022-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_reset_resized_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
