# Generated by Django 3.2.6 on 2022-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_group_is_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftBackup',
        ),
    ]
