# Generated by Django 3.2.6 on 2022-04-19 10:07

from django.db import migrations


def unvisualize_all_longtextfields(apps, schema_editor):
    GroupProfileFieldSetting = apps.get_model('core.GroupProfileFieldSetting')
    falsely_visible = GroupProfileFieldSetting.objects.filter(profile_field__field_type='html_field', show_field=True)
    falsely_visible.update(show_field=False)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0057_auto_20220314_1351'),
    ]

    operations = [
        migrations.RunPython(
            unvisualize_all_longtextfields,
            migrations.RunPython.noop
        )
    ]
