# Generated by Django 3.2.13 on 2022-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20220419_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='is_on_vcard',
            field=models.BooleanField(default=False),
        ),
    ]
