# Generated by Django 3.2.6 on 2022-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_profilefield_is_on_vcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='origin_token',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
