# Generated by Django 3.2.6 on 2022-04-19 12:46

from django.db import migrations


def unvisualize_all_longtextfields_common_overview(apps, schema_editor):
    ProfileField = apps.get_model('core.ProfileField')

    falsly_visible = ProfileField.objects.filter(field_type='html_field', is_in_overview=True)
    falsly_visible.update(is_in_overview=False)

    false_filter = ProfileField.objects.filter(field_type='html_field', is_filter=True)
    false_filter.update(is_filter=False)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0060_userprofile_origin_token'),
    ]

    operations = [
        migrations.RunPython(
            unvisualize_all_longtextfields_common_overview,
            migrations.RunPython.noop
        )
    ]
