# Generated by Django 3.2.13 on 2022-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20220419_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_submit_updates_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
