# Generated by Django 3.2.6 on 2022-04-01 09:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0062_group_is_submit_updates_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='tags',
            new_name='_tag_summary',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='tags',
            new_name='_tag_summary',
        ),
        migrations.AlterField(
            model_name='entity',
            name='_tag_summary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True,
                                                            db_column='tags', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='_tag_summary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True,
                                                            db_column='tags', default=list, size=None),
        ),
        migrations.CreateModel(
            name='TagSynonym',
            fields=[
                ('label', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms',
                                          to='core.tag')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EntityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.UUIDField()),
                ('author_label', models.CharField(max_length=256)),
                ('weight', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
    ]
