# Generated by Django 3.2.13 on 2022-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_add_depublication_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=255)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
