# Generated by Django 3.2.13 on 2022-06-24 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0065_searchqueryjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('mailer', models.CharField(max_length=255)),
                ('mailer_kwargs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('result', models.JSONField(blank=True, null=True)),
                ('mail_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mailinstance')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails_send_to_me', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails_sent_by_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
