# Generated by Django 3.2.13 on 2022-06-28 07:35

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_mailinstance_maillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='related_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(default=uuid.uuid4), blank=True, null=True, size=None),
        ),
    ]
