# Generated by Django 3.2.14 on 2022-07-15 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0067_entity_related_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
