# Generated by Django 3.2.14 on 2022-07-15 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0068_alter_entityview_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityview',
            name='session',
            field=models.TextField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entityview',
            name='viewer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
