# Generated by Django 3.2.14 on 2022-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20220720_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
