# Generated by Django 3.2.14 on 2022-08-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0008_filefolder_write_access_weight'),
        ('core', '0071_alter_revision_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('ready', 'Ready')], default='pending', max_length=11)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.filefolder')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
