# Generated by Django 3.2.14 on 2022-08-17 10:34
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_customagreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='object',
            new_name='_object',
        ),
        migrations.AlterField(
            model_name='revision',
            name='_object',
            field=models.ForeignKey(db_column='object', on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
        migrations.AddField(
            model_name='revision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='_object',
            new_name='_container',
        ),
        migrations.AlterField(
            model_name='revision',
            name='_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity'),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='last_revision',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='revision',
            name='unchanged',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='revision',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='previous_content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='group',
            name='featured_position_y',
            field=models.IntegerField(default=0),
        ),
    ]
