# Generated by Django 3.2.14 on 2022-07-15 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_revision_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='_category_summary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, db_column='categories', default=list, size=None),
        ),
        migrations.AddField(
            model_name='entity',
            name='category_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='_category_summary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, db_column='categories', default=list, size=None),
        ),
        migrations.AddField(
            model_name='group',
            name='category_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='overview_email_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
