# Generated by Django 3.2.16 on 2022-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0077_add_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='admin_weight',
            field=models.IntegerField(default=100),
        ),
    ]
