# Generated by Django 3.2.15 on 2022-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='widget_repository',
            field=models.JSONField(default=list, null=True),
        ),
    ]
