# Generated by Django 3.2.16 on 2023-02-03 12:02

from django.conf import settings
from django.db import migrations
from django.db import migrations, models
from django.db.models import Count, Max


def remove_duplicate_endpoints(apps, schema_editor):

    WebPushSubscription = apps.get_model("core", "WebPushSubscription")

    unique_fields = ['endpoint', 'user']

    duplicates = (
        WebPushSubscription.objects.values(*unique_fields)
        .order_by()
        .annotate(max_id=Max('id'), count_id=Count('id'))
        .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            WebPushSubscription.objects
            .filter(**{x: duplicate[x] for x in unique_fields})
            .exclude(id=duplicate['max_id'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0083_group_widget_repository'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_endpoints, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='webpushsubscription',
            unique_together={('endpoint', 'user')},
        ),
    ]
