# Generated by Django 3.2.18 on 2023-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_webpushsubscription_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteaccessrequest',
            options={'ordering': ('created_at',)},
        ),
    ]
