# Generated by Django 3.2.18 on 2023-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_groupmembership_notification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='attachments',
            field=models.JSONField(default=list),
        ),
    ]
