# Generated by Django 3.2.18 on 2023-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_revision_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_comment_notification_direct_mail_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_comment_notification_push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_comment_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mention_notification_direct_mail_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mention_notification_push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mention_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
