# Generated by Django 3.2.18 on 2023-05-09 14:11

import core.models.group
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_group_widget_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='plugins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=core.models.group._default_plugins, size=None),
        ),
    ]
