FETCH_PROFILE_URL = "/api/users/fetch_profile/{}"
FETCH_MAIL_PROFILE_URL="/api/users/fetch_profile_mail/{}"
REGISTER_ORIGIN_SITE_URL = "/api/users/register_origin_site/{}"
UPDATE_ORIGIN_SITE_URL = "/api/users/update_origin_site"
FETCH_AVATAR_URL = "/api/users/fetch_avatar/{}"
