serviceName: api

websitesAuto: []
websitesManual: []

annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/proxy-body-size: 2050m
  nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'

autoAnnotations:
  cert-manager.io/cluster-issuer: letsencrypt-pleio-prod-issuer
