serviceName: api

websitesAuto: []
websitesManual: []

annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/proxy-body-size: 2050m
  nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
  nginx.ingress.kubernetes.io/modsecurity-snippet: |
    SecRuleEngine On
    SecRule REQUEST_URI "@beginsWith /graphql" "id:1,ctl:ruleRemoveById=932110"
    SecRule REQUEST_URI "@beginsWith /graphql" "id:2,ctl:ruleRemoveById=932115"
    SecRule REQUEST_URI "@beginsWith /graphql" "id:3,ctl:ruleRemoveById=932105"
    SecRule REQUEST_URI "@beginsWith /graphql" "id:4,ctl:ruleRemoveById=932150"
    SecRule REQUEST_URI "@beginsWith /graphql" "id:5,ctl:ruleRemoveById=932100"
    SecRule REQUEST_URI "@beginsWith /graphql" "id:6,ctl:ruleRemoveById=949110"

autoAnnotations:
  cert-manager.io/cluster-issuer: letsencrypt-pleio-prod-issuer
