apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pleio2
  name: elasticsearch-test
  labels:
    app: elasticsearch-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-test
  template:
    metadata:
      labels:
        app: elasticsearch-test
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: elasticsearch-test
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        env:
          # NOTE: the cluster name; update this
          - name: cluster.name
            value: elasticsearch-cluster
          # NOTE: This will tell the elasticsearch node where to connect to other nodes to form a cluster
          - name: discovery.type
            value: "single-node"
          # NOTE: You can increase the heap size
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: elasticsearch-test
          mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
      volumes:
      - name: elasticsearch-test
        persistentVolumeClaim:
          claimName: elasticsearch-test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pleio2
  name: elasticsearch-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs
