# Generated by Django 2.2.6 on 2020-01-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Entity')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('rich_description', models.TextField(blank=True, null=True)),
                ('page_type', models.CharField(choices=[('campagne', 'Campagne'), ('text', 'Text')], max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('core.entity',),
        ),
    ]
