# Generated by Django 3.0.7 on 2020-07-14 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Entity')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('rich_description', models.TextField(blank=True, null=True)),
                ('page_type', models.CharField(choices=[('campagne', 'Campagne'), ('text', 'Text')], max_length=256)),
                ('position', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
            bases=('core.entity',),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('is_full_width', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cms.Page')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='cms.Page'),
        ),
        migrations.AddField(
            model_name='column',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='cms.Row'),
        ),
    ]
