# Generated by Django 2.2.6 on 2020-01-13 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('is_full_width', models.BooleanField(default=False)),
                ('parent_id', models.UUIDField(default=uuid.uuid4)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cms.Page')),
            ],
        ),
    ]
