# Generated by Django 2.2.6 on 2020-01-14 11:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('width', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('parent_id', models.UUIDField(default=uuid.uuid4)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='cms.Page')),
            ],
        ),
    ]
