# Generated by Django 3.0.8 on 2020-08-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200714_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position', 'created_at']},
        ),
    ]
