# Generated by Django 2.2.6 on 2020-01-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
