# Generated by Django 3.2.6 on 2022-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_page_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
    ]
