# Generated by Django 3.2.15 on 2022-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='row_repository',
            field=models.JSONField(default=list, null=True),
        ),
    ]
