# Generated by Django 3.1.2 on 2020-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='elgg_database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
