# Generated by Django 3.2.16 on 2022-11-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_agreementversion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='elgg_database',
        ),
    ]
