apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend2.name" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.secretKey  | b64enc }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId | b64enc }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc }}
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
  EMAIL_HOST: {{ .Values.email.host | b64enc }}
  EMAIL_PORT: {{ .Values.email.port | b64enc }}
