apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend2.name" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.secretKey  | b64enc }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId | b64enc }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc }}
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
{{- if .Values.dbReplica }}
  # This var is overridden for background-workers
  DB_HOST_REPLICA: {{ .Values.dbReplica.host | b64enc }}
{{- end }}
  EMAIL_HOST: {{ .Values.email.host | b64enc }}
  EMAIL_PORT: {{ .Values.email.port | b64enc }}
{{- if .Values.elasticsearch }}
  ELASTICSEARCH_HOST: {{ .Values.elasticsearch | b64enc }}
{{- end }}
{{- if .Values.ses }}
  AWS_SES_ACCESS_KEY_ID: {{ .Values.ses.accessKeyId | b64enc }}
  AWS_SES_REGION_ENDPOINT: {{ .Values.ses.regionEndpoint | b64enc }}
  AWS_SES_REGION_NAME: {{ .Values.ses.regionName | b64enc }}
  AWS_SES_SECRET_ACCESS_KEY: {{ .Values.ses.secretAccessKey | b64enc }}
{{- end }}
{{- if .Values.apm }}
  APM_ENABLED: {{ "True" | b64enc }}
  APM_SERVICE_NAME: {{ .Values.apm.serviceName | b64enc }}
  APM_TOKEN: {{ .Values.apm.token | b64enc }}
  APM_SERVER_URL: {{ .Values.apm.serverUrl | b64enc }}
{{- end }}
{{- if .Values.celery }}
  CELERY_BROKER_URL: {{ .Values.celery.brokerUrl | b64enc }}
  CELERY_RESULT_BACKEND: {{ .Values.celery.resultBackend | b64enc }}
{{- end}}
{{- if .Values.memcache }}
  MEMCACHE_ENABLED: {{ "True" | b64enc }}
  MEMCACHE_HOST_PORT: {{ .Values.memcache | b64enc }}
{{- end }}
{{- if .Values.clamav }}
  CLAMAV_HOST: {{ .Values.clamav | b64enc }}
{{- end }}
{{- if .Values.bouncer }}
  BOUNCER_URL: {{ .Values.bouncer.url | b64enc }}
  BOUNCER_TOKEN: {{ .Values.bouncer.token | b64enc }}
{{- end }}
{{- if .Values.accountApi }}
  ACCOUNT_API_URL: {{ .Values.accountApi.url | b64enc }}
  ACCOUNT_API_TOKEN: {{ .Values.accountApi.token | b64enc }}
{{- if .Values.accountApi.syncEnabled }}
  ACCOUNT_SYNC_ENABLED: {{ "True" | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.vapid }}
  VAPID_PUBLIC_KEY: {{ .Values.vapid.publicKey | b64enc }}
  VAPID_PRIVATE_KEY: {{ .Values.vapid.privateKey | b64enc }}
  VAPID_ADMIN_EMAIL: {{ .Values.vapid.adminEmail | b64enc }}
{{- end }}

--- 

{{- if .Values.tunnel.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend2.tunnelCredentials" . }}
data:
  credentials.json: {{ .Values.tunnel.credentials | b64enc }}
{{- end }}