apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend2.name" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.secretKey  | b64enc }}
  OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId | b64enc }}
  OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc }}
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
  EMAIL_HOST: {{ .Values.email.host | b64enc }}
  EMAIL_PORT: {{ .Values.email.port | b64enc }}
{{- if .Values.elasticsearch }}
  ELASTICSEARCH_HOST: {{ .Values.elasticsearch | b64enc }}
{{- end }}
{{- if .Values.s3 }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.s3.storageBucketName | b64enc }}
  AWS_S3_ENDPOINT_URL: {{ .Values.s3.endpointUrl | b64enc }}
  AWS_DEFAULT_ACL: {{ "private" | b64enc }}
{{- end }}
{{- if .Values.apm }}
  APM_ENABLED: {{ "True" | b64enc }}
  APM_SERVICE_NAME: {{ .Values.apm.serviceName | b64enc }}
  APM_TOKEN: {{ .Values.apm.token | b64enc }}
  APM_SERVER_URL: {{ .Values.apm.serverUrl | b64enc }}
{{- end }}
{{- if .Values.celery }}
  CELERY_BROKER_URL: {{ .Values.celery.brokerUrl | b64enc }}
  CELERY_RESULT_BACKEND: {{ .Values.celery.resultBackend | b64enc }}
{{- end}}
{{- if .Values.memcache }}
  MEMCACHE_ENABLED: {{ "True" | b64enc }}
  MEMCACHE_HOST_PORT: {{ .Values.memcache | b64enc }}
{{- end }}
{{- if .Values.clamav }}
  CLAMAV_HOST: {{ .Values.clamav | b64enc }}
{{- end }}
