# Generated by Django 2.2.2 on 2019-09-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='key',
            field=models.CharField(choices=[('bookmark', 'Bookmark')], default='bookmark', max_length=16),
        ),
    ]
