# Generated by Django 2.2.2 on 2019-09-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20190909_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
