# Generated by Django 3.2.16 on 2023-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_content', '0002_alter_externalcontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontentsource',
            name='last_full_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='externalcontentsource',
            name='last_update_sync',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
