# Generated by Django 3.2.6 on 2022-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_remove_question_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
