# Generated by Django 2.2.2 on 2019-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='rich_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
