# Generated by Django 3.0.8 on 2020-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
