# Generated by Django 3.1.5 on 2021-01-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('discussion', '0002_discussion_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='featured_alt',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='discussion',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='file.filefolder'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='featured_position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='featured_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
