# Generated by Django 2.2.2 on 2019-07-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_object'),
        ('discussion', '0002_auto_20190709_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='read_access',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='write_access',
        ),
        migrations.AddField(
            model_name='discussion',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Object'),
            preserve_default=False,
        ),
    ]
