# Generated by Django 3.1.8 on 2021-06-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussion_featured_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-published']},
        ),
    ]
