# Generated by Django 2.0 on 2018-07-16 15:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180513_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Group'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=['private'], size=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='write_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=['private'], size=None),
        ),
    ]
