# Generated by Django 3.1.8 on 2021-06-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_featured_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published']},
        ),
    ]
