# Generated by Django 2.2.2 on 2019-08-15 13:13

import core.lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190710_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to=core.lib.generate_object_filename),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_video',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
