# Generated by Django 2.2.2 on 2019-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190822_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_featured',
            new_name='is_recommended',
        ),
        migrations.AddField(
            model_name='blog',
            name='rich_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
