# Generated by Django 3.2.6 on 2022-02-03 14:53

from django.db import migrations


def forward_update_entity(apps, schema_editor):
    pass

def reverse_update_entity(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    Blog.objects.filter(tmp_is_featured=True).update(is_featured=True)
    Blog.objects.filter(tmp_is_recommended=True).update(is_recommended=True)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220203_1503'),
    ]

    run_before = [
        ('core', '0051_auto_20220203_1553'),
    ]

    operations = [
        migrations.RunPython(forward_update_entity, reverse_update_entity),
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_recommended',
        ),
    ]
