# Generated by Django 3.1.2 on 2020-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
