# Generated by Django 3.1.4 on 2021-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201123_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_alt',
            field=models.CharField(default='', max_length=256),
        ),
    ]
