# Generated by Django 3.2.6 on 2021-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
