# Generated by Django 3.2.6 on 2022-02-03 14:53

from django.db import migrations

def forward_update_entity(apps, schema_editor):
    pass

def reverse_update_entity(apps, schema_editor):
    Event = apps.get_model('event', 'Event')
    Event.objects.filter(tmp_is_featured=True).update(is_featured=True)

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_rename_is_featured_event_old_featured'),
    ]

    run_before = [
        ('core', '0051_auto_20220203_1553'),
    ]

    operations = [
        migrations.RunPython(forward_update_entity, reverse_update_entity),
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
    ]
