# Generated by Django 3.2.6 on 2022-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='state',
            field=models.CharField(choices=[('accept', 'Accept'), ('maybe', 'Maybe'), ('reject', 'Reject'), ('waitinglist', 'Waitinglist')], max_length=16),
        ),
    ]
