# Generated by Django 3.2.6 on 2022-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventattendee_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='location_link',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
