# Generated by Django 3.2.6 on 2022-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_eventattendee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='location_link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
