# Generated by Django 3.2.13 on 2022-05-12 10:16

from django.db import migrations


def update_attendees_with_user_name_mail(apps, schema_editor):
    EventAttendee = apps.get_model('event', 'EventAttendee')
    for attendee in EventAttendee.objects.filter(user__isnull=False):
        attendee.name = attendee.user.name
        attendee.email = attendee.user.email
        attendee.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0016_auto_20220422_1035'),
    ]

    operations = [
        migrations.RunPython(update_attendees_with_user_name_mail, migrations.RunPython.noop)
    ]
