# Generated by Django 3.2.13 on 2022-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20220422_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
