# Generated by Django 3.2.13 on 2022-06-02 08:06

from django.db import migrations


def ensure_attendees_have_mail(apps, schema_editor):
    EventAttendee = apps.get_model('event', 'EventAttendee')
    for attendee in EventAttendee.objects.filter(email__isnull=True):
        if attendee.user:
            attendee.email = attendee.user.email
        else:
            attendee.email = 'info@pleio.nl'
        attendee.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0018_update_attendees_with_user_name_mail'),
    ]

    operations = [
        migrations.RunPython(ensure_attendees_have_mail, migrations.RunPython.noop)
    ]
