# Generated by Django 3.2.13 on 2022-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_ensure_attendees_have_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='state',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('maybe', 'Maybe'), ('reject', 'Reject'), ('waitinglist', 'Waitinglist')], max_length=16, null=True),
        ),
    ]
