# Generated by Django 3.2.13 on 2022-06-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_attendee_requires_email_state_is_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_available', to='event.event')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventslot'),
        ),
    ]
