# Generated by Django 3.2.14 on 2022-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_event_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slot',
        ),
        migrations.AddField(
            model_name='event',
            name='slots_available',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='EventSlot',
        ),
    ]
