# Generated by Django 3.2.14 on 2022-07-30 09:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_slots_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shared_via_slot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None),
        ),
    ]
