# Generated by Django 3.2.14 on 2022-09-28 12:07

from django.db import migrations, models
from django.db.models import Count, Max

from event.models import EventAttendee


def remove_duplicates(apps, schema_editor):

    EventAttendee = apps.get_model("event", "EventAttendee")

    unique_fields = ['event', 'email']

    duplicates = (
        EventAttendee.objects.values(*unique_fields)
        .order_by()
        .annotate(max_id=Max('id'), count_id=Count('id'))
        .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            EventAttendee.objects
            .filter(**{x: duplicate[x] for x in unique_fields})
            .exclude(id=duplicate['max_id'])
            .delete()
        )

    unique_fields = ['event', 'user']

    duplicates = (
        EventAttendee.objects.values(*unique_fields)
        .order_by()
        .annotate(max_id=Max('id'), count_id=Count('id'))
        .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            EventAttendee.objects
            .filter(**{x: duplicate[x] for x in unique_fields})
            .exclude(id=duplicate['max_id'])
            .delete()
        )



class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_event_shared_via_slot'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_user'),
        ),
    ]
