# Generated by Django 3.2.14 on 2022-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_event_shared_via_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_user'),
        ),
    ]
