# Generated by Django 3.2.16 on 2022-12-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20220928_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee_welcome_mail_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_welcome_mail_subject',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
