# Generated by Django 3.2.18 on 2023-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20230112_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='index_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='range_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='range_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='range_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='range_members', to='event.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='range_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='range_starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
