# Generated by Django 3.2.18 on 2023-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_event_range_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_maybe_attend_event',
            field=models.BooleanField(default=True),
        ),
    ]
