from ariadne import ObjectType

from event.resolvers.mutation_attend_event import resolve_attend_event, resolve_attend_event_without_account
from event.resolvers.mutation_confirm_attend_event_without_account import resolve_confirm_attend_event_without_account
from event.resolvers.mutation_delete_event_attendees import resolve_delete_event_attendees
from event.resolvers.mutation_edit_event_attendee import resolve_edit_event_attendee
from event.resolvers.mutation_messages import resolve_send_message_to_event

mutation = ObjectType("Mutation")

mutation.set_field("attendEvent", resolve_attend_event)
mutation.set_field("attendEventWithoutAccount", resolve_attend_event_without_account)
mutation.set_field("confirmAttendEventWithoutAccount", resolve_confirm_attend_event_without_account)
mutation.set_field("editEventAttendee", resolve_edit_event_attendee)
mutation.set_field("deleteEventAttendees", resolve_delete_event_attendees)
mutation.set_field("sendMessageToEvent", resolve_send_message_to_event)
