# Generated by Django 2.2.6 on 2019-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='rich_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
