# Generated by Django 3.1.2 on 2020-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
