# Generated by Django 3.2.6 on 2022-01-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_statusupdate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-published'], 'verbose_name': 'status update'},
        ),
    ]
