# Generated by Django 3.2.6 on 2022-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_statusupdate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusupdate',
            name='description',
        ),
    ]
