# Generated by Django 2.0 on 2018-07-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='object_id',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='content_type',
            new_name='node_type',
        ),
    ]
