# Generated by Django 2.2.2 on 2019-07-09 15:18

import django.contrib.postgres.fields
from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180717_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='read_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=feed.models.default_read_access, size=None),
        ),
        migrations.AlterField(
            model_name='feed',
            name='write_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=feed.models.default_write_access, size=None),
        ),
    ]
