# Generated by Django 2.2.2 on 2019-09-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190709_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
