# Generated by Django 2.2.6 on 2019-10-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190924_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Entity')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('rich_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('core.entity',),
        ),
    ]
