# Generated by Django 3.1.8 on 2021-06-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-published']},
        ),
    ]
