# Generated by Django 2.2.6 on 2019-10-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
