# Generated by Django 2.2.6 on 2019-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('BUSY', 'Busy'), ('DONE', 'Done')], default='NEW', max_length=32),
        ),
    ]
