{{ $labelData := dict "Values" .Values "Release" .Release "Chart" .Chart "Component" "admin" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend2.adminName" . }}
  labels:
    {{- include "backend2.labels" $labelData | nindent 4 }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend2.selectorLabels" $labelData | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ include "backend2.adminName" . }}
      labels:
        {{- include "backend2.selectorLabels" $labelData | nindent 8 }}
        environment: {{ .Values.env }}
    spec:
      initContainers:
        - name: init-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['python', 'manage.py', 'migrate_schemas']
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "backend2.name" . }}
            - secretRef:
                name: {{ include "backend2.secretsName" . }}
          env:
            - name: RUN_AS_ADMIN_APP
              value: "True"
            - name: DB_HOST_REPLICA
              value: ""
      containers:
        - name: {{ include "backend2.adminName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - /start-admin.sh
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app-data
              name: pleio-data
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ include "backend2.name" . }}
            - secretRef:
                name: {{ include "backend2.secretsName" . }}
          env:
            - name: RUN_AS_ADMIN_APP
              value: "True"
            - name: DB_HOST_REPLICA
              value: ""
        {{- if .Values.tunnel.hostname }}
        - name: tunnel
          image: "{{ .Values.tunnel.repository }}:{{ .Values.tunnel.tag }}"
          command:
            - cloudflared
            - tunnel
          args:
            - --url=http://127.0.0.1:8000
            - --hostname={{ .Values.tunnel.hostname }}
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
          volumeMounts:
            - mountPath: /etc/cloudflared
              name: tunnel-secret
              readOnly: true
        {{- end }}
      volumes:
        - name: pleio-data
          {{- if eq .Values.storage.type "hostpath" }}
          hostPath:
            path: {{ .Values.storage.existingDataStorage }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "backend2.dataStorageName" . }}
          {{- end }}
        {{- if .Values.tunnel.hostname }}
        - name: tunnel-secret
          secret:
            defaultMode: 420
            secretName: {{ .Values.tunnel.secretname }}
        {{- end }}
