{{ $labelData := dict "Values" .Values "Release" .Release "Chart" .Chart "Component" "api" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend2.apiName" . }}
  labels:
    {{- include "backend2.labels" $labelData | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend2.selectorLabels" $labelData | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ add .Values.api.replicaCount 1 }}
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: {{ include "backend2.apiName" . }}
      labels:
        {{- include "backend2.selectorLabels" $labelData | nindent 8 }}
        environment: {{ .Values.env }}
    spec:
      initContainers:
      - name: {{ include "backend2.frontendName" . }}
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: {{ .Values.frontend.pullPolicy }}
        command:
          - cp
          - -R
          - /usr/share/nginx/html/.
          - /frontend
        volumeMounts:
          - mountPath: /frontend
            name: frontend
      containers:
        - name: {{ include "backend2.apiName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /start.sh
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp-zip-storage
            - mountPath: /app-data
              name: pleio-data
            - mountPath: /app/static-frontend
              name: frontend
          envFrom:
            - configMapRef:
                name: {{ include "backend2.name" . }}
            - secretRef:
                name: {{ include "backend2.secretsName" . }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: tmp-zip-storage
          {{- if eq .Values.storage.type "hostpath" }}
          hostPath:
            path: {{ .Values.storage.existingTempStorage }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "backend2.tempStorageName" . }}
          {{- end }}
        - name: pleio-data
          {{- if eq .Values.storage.type "hostpath" }}
          hostPath:
            path: {{ .Values.storage.existingDataStorage }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "backend2.dataStorageName" . }}
          {{- end }}
        - name: frontend
          emptyDir: {}
