apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend2.name" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.env }}
  DEBUG: {{ .Values.debug | quote }}
  ALLOWED_HOST: "*"
  OIDC_RP_SCOPES: openid profile email
  OIDC_OP_AUTHORIZATION_ENDPOINT: {{ printf "%s/openid/authorize/" .Values.accountDomain }}
  OIDC_OP_TOKEN_ENDPOINT: {{ printf "%s/openid/token/" .Values.accountDomain }}
  OIDC_OP_USER_ENDPOINT: {{ printf "%s/openid/userinfo/" .Values.accountDomain }}
  OIDC_OP_LOGOUT_ENDPOINT: {{ printf "%s/action/logout" .Values.accountDomain }}
  PROFILE_PICTURE_URL: {{ printf "%s" .Values.accountDomain }}
  FROM_EMAIL: noreply@mail.pleio.nl
  MEDIA_ROOT: /app-data
  BACKUP_PATH: /backup-storage
  CSP_REPORT_ONLY: {{ .Values.cspReportOnly | quote }}
  ENDPOINT_2FA: {{ printf "%s/securitypages" .Values.accountDomain }}
  ONLINE_MEETINGS_URL: {{ .Values.onlineMeetingsUrl }}
  VIDEO_CALL_RESERVE_ROOM_URL: {{ .Values.videoCallReserveRoomUrl }}
  CONTROL_PRIMARY_DOMAIN: {{ .Values.tunnel.hostname }}
  SCAN_CYCLE_DAYS: {{ .Values.clamav.scanCycleDays }}
