{{- $serviceName := ((include "backend2.apiName" .)) -}}
---
{{- if or .Values.websitesAuto .Values.adminDomain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.autoAnnotations -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-auto-certs" ((include "backend2.name" .)) }}
spec:
  rules:
  {{- range .Values.websitesAuto }}
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
            path: '/'
            pathType: Prefix
  {{- end }}
  {{- if .Values.adminDomain }}
    - host: {{ .Values.adminDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "backend2.adminName" . }}
                port:
                  name: http
            path: '/'
            pathType: Prefix
  {{- end }}
  tls:
  {{- range .Values.websitesAuto }}
    - hosts:
        - {{ .domain | quote }}
        - {{ printf "www.%s" .domain | quote }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- if .Values.adminDomain }}
    - hosts:
        - {{ .Values.adminDomain }}
        - {{ printf "www.%s" .Values.adminDomain | quote }}
      secretName: {{ include "backend2.tlsSecretName" . }}
  {{- end }}
{{- end }}
---
{{- if .Values.websitesManual }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- with .Values.ingress.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.manualAnnotations -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-manual-certs" ((include "backend2.name" .)) }}
spec:
  rules:
  {{- range .Values.websitesManual }}
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $serviceName }}
                port:
                  name: http
            path: '/'
            pathType: Prefix
  {{- end }}
  tls:
  {{- range .Values.websitesManual }}
    - hosts:
        - {{ .domain | quote }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
