apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend2.tempStorageName" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.tmpSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "backend2.dataStorageName" . }}
  labels:
    {{- include "backend2.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}
