# Generated by Django 2.0 on 2018-07-17 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180717_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
