# Generated by Django 3.1.2 on 2020-10-13 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_ban_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superadmin',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
