# Generated by Django 3.1.2 on 2020-11-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_login_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_count',
        ),
    ]
