# Generated by Django 3.1.7 on 2021-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
