replicaCount: 1
accountDomain: https://account2.pleio-test.nl
adminDomain: review-admin.pleio-test.nl
domains:
  - review.pleio-test.nl

frontend:
  repository: registry.gitlab.com/pleio/frontend
  tag: B2-latest
  pullPolicy: Always

admin:
  replicaCount: 1

api:
  replicaCount: 1

image:
  repository: registry.gitlab.com/pleio/backend2
  tag: latest
  pullPolicy: IfNotPresent

storage:
   className: efs
   dataSize: 1Mi
   tmpSize: 1Mi

ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-pleio-prod-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
