accountDomain:
adminDomain:
# Websites that require manual certs
websitesManual: []
# - domain: *.pleio.nl
#   secretName: tls-wildcard.pleio.nl
websitesAuto: []
# - domain: www.pleio-extra.nl
#   secretName: tls-pleio-extra.nl

env: test
debug: 'False'

frontend:
  repository: registry.gitlab.com/pleio/frontend
  tag: B2-latest
  pullPolicy: Always

admin:
  replicaCount: 1

api:
  replicaCount: 1

background:
  replicaCount: 1

image:
  repository: registry.gitlab.com/pleio/backend2
  tag: latest
  pullPolicy: IfNotPresent

storage:
  className: efs
  dataSize: 1Mi
  tmpSize: 1Mi
  backupSize: 1Mi
  existingTempStorage:
  existingDataStorage:
  existingBackupStorage:

cleanup:
  # The schedule for which the clean job will be run
  schedule: '0 2 * * *' # every day at 2 in the morning
  # The maximum amount of days, a file will exist in the tmp folder
  maxFileAge: 2

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
  issuerAnnotation: 'cert-manager.io/issuer: letsencrypt-pleio-prod-issuer'

memcached:
  persistence:
    enabled: false
