accountDomain: https://account.pleio.nl
websitesManual:
  - domain: '*.pleio.nl'
    secretName: tls-wildcard.pleio.nl

cspReportOnly: 'False'

api:
  replicaCount: 14

background:
  replicaCount: 2

env: prod

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
 requests:
   cpu: 1000m
  # memory: 128Mi


storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2/tmp
  existingDataStorage: /storage/_pleio2/data
  existingBackupStorage: /storage/backup-storage

tunnel:
  hostname: admin-odcn-prod.pleio-beheer.nl
