accountDomain: https://account.pleio.nl
websitesManual:
  - domain: '*.pleio.nl'
    secretName: tls-wildcard.pleio.nl

cspReportOnly: 'False'

api:
  replicaCount: 14
  resources:
    limits:
      cpu: 1500m
      memory: 1536Mi
    requests:
      cpu: 500m
      memory: 1024Mi

background:
  worker:
    replicaCount: 4
    resources:
      limits:
        cpu: 2500m
        memory: 2048Mi
      requests:
        cpu: 1500m
        memory: 2048Mi
  scheduler:
    resources:
      limits:
        cpu: 750m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 250Mi

admin:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 250Mi

env: prod

storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2/tmp
  existingDataStorage: /storage/_pleio2/data
  existingBackupStorage: /storage/backup-storage

tunnel:
  hostname: admin-odcn-prod.pleio-beheer.nl

collab:
  backend: collab-backend
