accountDomain: https://account.pleio-test.nl
websitesManual:
  - domain: 'review.pleio-test.nl'
    secretName: tls-wildcard.pleio-test.nl
  - domain: 'collab.pleio-test.nl'
    secretName: tls-wildcard.pleio-test.nl

cspReportOnly: 'False'

api:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

background:
  worker:
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 1024Mi
  scheduler:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 250Mi

admin:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 250Mi

storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2-review/tmp
  existingDataStorage: /storage/_pleio2-review/data
  existingBackupStorage: /storage/backup-storage

tunnel:
  hostname: admin-odcn-review.pleio-beheer.nl

collab:
  backend: collab-backend-test
