accountDomain: https://account.pleio.nl
websitesManual:
  - domain: '*.pleio.nl'
    secretName: tls-wildcard.pleio.nl

cspReportOnly: 'False'

api:
  replicaCount: 8
  resources:
    limits:
      cpu: 1500m
      memory: 1536Mi
    requests:
      cpu: 1500m
      memory: 1536Mi

background:
  worker:
    replicaCount: 8
    resources:
      limits:
        cpu: 400m
        memory: 2048Mi
      requests:
        cpu: 400m
        memory: 2048Mi
  scheduler:
    resources:
      limits:
        cpu: 750m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 250Mi

admin:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 250Mi
  tunnelConfig: |
    tunnel: control
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: control.pleio-beheer.nl
      service: http://127.0.0.1:8000
    - service: http_status:404

env: prod

storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2/tmp
  existingDataStorage: /storage/_pleio2/data
  existingBackupStorage: /storage/backup-storage

tunnel:
  hostname: control.pleio-beheer.nl

collab:
  backend: collab-backend

videoCallReserveRoomUrl: https://videobellen.pleio.nl/api/v1/room/

clamav:
  scanCycleDays: 60