accountDomain: https://account.pleio.nl
websitesManual:
  - domain: '*.pleio.nl'
    secretName: tls-wildcard.pleio.nl

cspReportOnly: 'False'

api:
  replicaCount: 14

background:
  replicaCount: 0

admin:
  replicaCount: 0

storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2-test/tmp
  existingDataStorage: /storage/_pleio2-test/data
  existingBackupStorage: /storage/backup-storage
