accountDomain: https://account.pleio.nl
adminDomain: admin.pleio-test.nl
websitesManual:
  - domain: '*.pleio-test.nl'
    secretName: tls-wildcard.pleio-test.nl

api:
  replicaCount: 2

background:
  replicaCount: 1

storage:
  existingBackupStorage: backup-storage
  existingDataStorage: pleio-data-test

ingress:
  autoAnnotations:
    cert-manager.io/cluster-issuer: letsencrypt-pleio-prod-issuer
    cert-manager.io/issuer:
