accountDomain: https://account.pleio.nl
websitesManual:
  - domain: '*.pleio-test.nl'
    secretName: tls-wildcard.pleio-test.nl

cspReportOnly: 'False'

api:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

background:
  worker:
    replicaCount: 2
    resources:
      limits:
        cpu: 300m
        memory: 2048Mi
      requests:
        cpu: 300m
        memory: 2048Mi
  scheduler:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 250Mi

admin:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 250Mi

storage:
  type: hostpath
  existingTempStorage: /storage/_pleio2-test/tmp
  existingDataStorage: /storage/_pleio2-test/data
  existingBackupStorage: /storage/backup-storage

tunnel:
  hostname: control-test.pleio-beheer.nl

collab:
  backend: collab-backend-test
