# Generated by Django 2.2.11 on 2020-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200419_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ['id']},
        ),
    ]
