# Generated by Django 3.2.6 on 2022-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
    ]
