# Generated by Django 3.2.18 on 2023-05-12 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_groupcopy_copy_members'),
        ('control', '0004_accesslog_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.CharField(max_length=255)),
                ('result', models.JSONField(default=dict)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_operation_log', to='tenants.client')),
            ],
            options={
                'ordering': ('operation', '-created_at'),
            },
        ),
    ]
