# Generated by Django 3.1.6 on 2021-02-23 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.IntegerField()),
                ('object_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
